### ISSUE TITLE
Files missing in .sln

### ISSUE THREAD

**Issue by kah-heng** [joecastro/wpf-shell#4]
Hi Joe,

I am running into some issues when I am trying to use the windows.shell for my project to create a custom chrome frameless window.

I am launching a wpf window from another application but when I try to load a file inside my wpf window application, the chrome 'blacks out'. I am unsure if this is a bug in the shell library but it sounds very similar to a post you had commented on here: http://archive.msdn.microsoft.com/WPFShell/Thread/View.aspx?ThreadId=3984
The issue similarly resolves upon window maximize.

The version I am using is the old version found on http://archive.msdn.microsoft.com/WPFShell

So I followed your suggested suggestion and went to fishbowl to get the updated Microsoft.Windows.Shell.dll from the project but when I reference it inside my project, it could not work and gives reference to Null error. I am not sure what is the issue there hence I went ahead and downloaded the source code from GitHub to attempt a compile. However the compile could not happen as there are some files missing:
![image](https://f.cloud.github.com/assets/4847382/1113923/6b7c4fce-1a0a-11e3-8058-855f2714d680.png)

Hope that you will be able to provide me with some insights into solving the blacking out problem. Thank you!

**Comment by joecastro** [comment]
Fixed with 104c44556f50a3b77ae10d43c6a0cac6b2dd2fac
